import '../../utils/imports.dart';

/// Data model representing a customer in the system.
class Customer extends Equatable {
  /// Unique identifier generated by the database.
  final String customerId;

  /// Full name of the customer.
  final String name;

  /// Contact phone number.
  final String phoneNumber;

  /// Residential or temporary address.
  final String address;

  const Customer({
    required this.customerId,
    required this.name,
    required this.phoneNumber,
    required this.address,
  });

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'phoneNumber': phoneNumber,
      'address': address,
    };
  }

  factory Customer.fromJson(String id, Map<String, dynamic> json) {
    return Customer(
      customerId: id,
      name: json['name'] ?? '',
      phoneNumber: json['phoneNumber'] ?? '',
      address: json['address'] ?? '',
    );
  }

  Customer copyWith({
    String? customerId,
    String? name,
    String? phoneNumber,
    String? address,
  }) {
    return Customer(
      customerId: customerId ?? this.customerId,
      name: name ?? this.name,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      address: address ?? this.address,
    );
  }

  @override
  List<Object?> get props => [
        customerId,
        name,
        phoneNumber,
        address,
      ];
}
