import '../../utils/imports.dart';

/// Data model representing a maintenance record for a bike.
class Maintenance extends Equatable {
  /// Unique identifier generated by the database.
  final String maintenanceId;

  /// The registration plate of the bike that underwent maintenance.
  final String bikeId;

  /// The date the maintenance was performed.
  final DateTime date;

  /// Description of the parts replaced or service performed.
  final String parts;

  /// Total cost of the maintenance.
  final double price;

  const Maintenance({
    required this.maintenanceId,
    required this.bikeId,
    required this.date,
    required this.parts,
    required this.price,
  });

  Map<String, dynamic> toJson() => {
        'bikeId': bikeId,
        'date': date.toIso8601String(),
        'parts': parts,
        'price': price,
      };

  factory Maintenance.fromJson(String id, Map<String, dynamic> json) =>
      Maintenance(
        maintenanceId: id,
        bikeId: json['bikeId'],
        date: DateTime.parse(json['date']),
        parts: json['parts'],
        price: (json['price'] as num).toDouble(),
      );

  Maintenance copyWith({
    String? bikeId,
    DateTime? date,
    String? parts,
    double? price,
  }) {
    return Maintenance(
      maintenanceId: maintenanceId,
      bikeId: bikeId ?? this.bikeId,
      date: date ?? this.date,
      parts: parts ?? this.parts,
      price: price ?? this.price,
    );
  }

  @override
  List<Object?> get props => [
        maintenanceId,
        bikeId,
        date,
        parts,
        price,
      ];
}
