import '../../utils/imports.dart';

/// Constants representing payment statuses for a rental.
class RentalStatusConstants {
  static const String paid = 'Paid';
  static const String pending = 'Pending';
}

/// Returns a localized string for the given payment [statusConstant].
String getLocalizedPaymentStatus(
    String statusConstant, AppLocalizations appStrings) {
  switch (statusConstant) {
    case RentalStatusConstants.paid:
      return appStrings.paymentStatusPaid;
    case RentalStatusConstants.pending:
      return appStrings.paymentStatusPending;
    default:
      return appStrings.paymentStatusPending;
  }
}

/// Data model representing a bike rental transaction.
class Rental extends Equatable {
  /// Unique identifier generated by the database.
  final String rentalId;

  /// The registration plate of the rented bike.
  final String bikeId;

  /// The ID of the customer who rented the bike.
  final String customerId;

  /// The start date and time of the rental.
  final DateTime startDate;

  /// The scheduled end date and time of the rental.
  final DateTime endDate;

  /// The actual date and time the bike was returned.
  final DateTime? returnDate;

  /// The final agreed price for the rental period.
  final double finalPrice;

  /// The amount of monetary deposit held.
  final double depositAmount;

  /// Current payment status (see [RentalStatusConstants]).
  final String paymentStatus;

  /// Whether a physical document (like an ID card) was left as a deposit.
  final bool documentDepositProvided;

  const Rental({
    required this.rentalId,
    required this.bikeId,
    required this.customerId,
    required this.startDate,
    required this.endDate,
    required this.finalPrice,
    required this.depositAmount,
    required this.paymentStatus,
    required this.documentDepositProvided,
    this.returnDate,
  });

  Rental copyWith({
    String? rentalId,
    String? bikeId,
    String? customerId,
    DateTime? startDate,
    DateTime? endDate,
    double? finalPrice,
    double? depositAmount,
    String? paymentStatus,
    bool? documentDepositProvided,
    DateTime? returnDate,
  }) {
    return Rental(
      rentalId: rentalId ?? this.rentalId,
      bikeId: bikeId ?? this.bikeId,
      customerId: customerId ?? this.customerId,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      finalPrice: finalPrice ?? this.finalPrice,
      depositAmount: depositAmount ?? this.depositAmount,
      paymentStatus: paymentStatus ?? this.paymentStatus,
      documentDepositProvided:
          documentDepositProvided ?? this.documentDepositProvided,
      returnDate: returnDate ?? this.returnDate,
    );
  }

  Map<String, dynamic> toJson() => {
        'bikeId': bikeId,
        'customerId': customerId,
        'startDate': startDate.toIso8601String(),
        'endDate': endDate.toIso8601String(),
        'finalPrice': finalPrice,
        'depositAmount': depositAmount,
        'paymentStatus': paymentStatus,
        'documentDepositProvided': documentDepositProvided,
        'returnDate': returnDate?.toIso8601String(),
      };

  factory Rental.fromJson(String id, Map<String, dynamic> json) {
    return Rental(
      rentalId: id,
      bikeId: json['bikeId'],
      customerId: json['customerId'],
      startDate: DateTime.parse(json['startDate']),
      endDate: DateTime.parse(json['endDate']),
      finalPrice: (json['finalPrice'] as num).toDouble(),
      depositAmount: (json['depositAmount'] as num).toDouble(),
      paymentStatus: json['paymentStatus'],
      documentDepositProvided: json['documentDepositProvided'],
      returnDate: json['returnDate'] != null
          ? DateTime.parse(json['returnDate'])
          : null,
    );
  }

  @override
  List<Object?> get props => [
        rentalId,
        bikeId,
        customerId,
        startDate,
        endDate,
        finalPrice,
        depositAmount,
        paymentStatus,
        documentDepositProvided,
        returnDate,
      ];
}
